trigger:
  - master
  
pool:
    vmImage: ubuntu-latest

stages:
- stage: build_test
  jobs:
  - job: build_job
    steps:       
      - script: |
          sudo apt-get update
          pip install --upgrade databricks-cli
         # sudo apt-get install software-properties-common
         # sudo apt-get install python3.9
         # sudo apt install python3-pip 
         # pip install checkov
        displayName: 'Requirements'
        workingDirectory: $(System.DefaultWorkingDirectory)

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: "service-connect-vault-access"
          KeyVaultName: 'kv-razi'
          SecretsFilter: 'client-id, client-secret, tenant-id'
        displayName: 'Azure Key Vault Secrets'

      - script: |
          az login --service-principal -u $(client-id) -p $(client-secret) --tenant $(tenant-id)
        displayName: 'Azure authenticate'
        workingDirectory: $(System.DefaultWorkingDirectory)/
     
      - script: |
          terraform init -upgrade
          terraform fmt
          terraform validate
          terraform plan -out=tfplan
        displayName: 'Export Terraform Validate'
        workingDirectory: $(System.DefaultWorkingDirectory)/

      - script: |
          terraform apply -auto-approve tfplan
        displayName: 'Terraform run'
        workingDirectory: $(System.DefaultWorkingDirectory)/