# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      terraform init
      terraform validate
    displayName: 'Terraform Init and Validate'

  - script: |
      export ARM_CLIENT_ID=$(AzureServicePrincipleId)
      export ARM_CLIENT_SECRET=$(AzureServicePrincipleKey)
      export ARM_SUBSCRIPTION_ID=$(AzureSubscriptionId)
      export ARM_TENANT_ID=$(AzureTenantId)

      #deploy terraform
      terraform apply -auto-approve
    displayName: 'Authenticate to Azure'
    env:
      AzureServicePrincipleId: $(ARM_CLIENT_ID)
      AzureServicePrincipleKey: $(ARM_CLIENT_CLIENT_SECRET)
      AzureSubscriptionId: $(ARM_SUBSCRIPTION_ID)
      AzureTenantId: $(ARM_TENANT_ID)
    workingDirectory: $(System.DefaultWorkingDirectory)

  
    