# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      terraform init
      terraform validate
    displayName: 'Terraform Init and Validate'

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
   
  - script: |
      terraform init
      terraform apply -auto-approve
    displayName: "Run Terraform"


  
    